import { parseJson, type JsonValue } from './json.js';
import WebSocket from 'ws';
import { AuthError, APIError } from './errors.js';
import { channelMetadataFromDict, eventFromRecord, eventFromReplay, forkReceiptFromDict, type ChannelMetadata, type Event, type ForkReceipt } from './types.js';
import { manifestOperation, type ManifestOperation } from './manifest.js';
import { newUUID } from './uuid.js';

export interface FleetClientOptions { organizationToken: string; endpoint: string; organizationId?: string; tokenEndpoint?: string; fetch?: typeof globalThis.fetch; requestedScopes?: string[] }
export const DEFAULT_FLEET_SCOPES = ['events:read','events:write','state:read','state:write','channels:read','channels:write','forks:create'];
export interface FleetRequestOptions { instanceId?: string; signal?: AbortSignal; idempotencyKey?: string; confirmTarget?: string }
export interface InstanceError { instanceId: string; code: string; message: string; retryable: boolean }
export interface Page<T> { items: T[]; nextPageToken?: string }
export interface PartialResult<T> extends Page<T> { errors: InstanceError[]; pageTokens?: Record<string,string> }
export interface FleetStreamReconnectOptions extends FleetRequestOptions { ticket?: string; ticketProvider?: (resumeCursor?: bigint | string | number) => Promise<string>; resumeCursor?: bigint | string | number; maxReconnectAttempts?: number; reconnectDelayMs?: number; params?: Record<string,string|number|undefined>; maxQueueFrames?: number }
export function requireComplete<T>(result: PartialResult<T>): T[] { if(result.errors.length) throw new APIError(502, `partial fleet result: ${result.errors.map((e)=>`${e.instanceId}: ${e.code}`).join(', ')}`); return result.items; }

/** Server-side fleet client. Organization credentials never leave token exchange. */
export class FleetClient {
  private readonly endpoint: string; private readonly organizationToken: string; private readonly organizationId: string;
  private readonly fetcher: typeof globalThis.fetch; private readonly tokenEndpoint: string; private fleetToken?: string; private expiresAt = 0; private exchange?: Promise<string>;
  private readonly requestedScopes: string[];
  private readonly capabilitiesCache = new Map<string, JsonValue>();
  constructor(opts: FleetClientOptions) { if (!opts.organizationToken || !opts.endpoint) throw new Error('organizationToken and endpoint are required'); this.organizationToken=opts.organizationToken; this.organizationId=opts.organizationId ?? 'default'; this.endpoint=opts.endpoint.replace(/\/+$/,''); this.tokenEndpoint=(opts.tokenEndpoint??this.endpoint).replace(/\/+$/,''); this.fetcher=opts.fetch ?? globalThis.fetch; this.requestedScopes=opts.requestedScopes??DEFAULT_FLEET_SCOPES; }
  static fromEnv(overrides: Partial<FleetClientOptions> = {}): FleetClient { const env=typeof process!=='undefined'?process.env:{}; return new FleetClient({ endpoint:overrides.endpoint ?? env.ACTAE_FLEET_URL ?? '', tokenEndpoint:overrides.tokenEndpoint ?? env.ACTAE_FLEET_TOKEN_URL, organizationToken:overrides.organizationToken ?? env.ACTAE_ORG_TOKEN ?? '', organizationId:overrides.organizationId ?? env.ACTAE_ORG_ID, fetch:overrides.fetch, requestedScopes:overrides.requestedScopes??(env.ACTAE_FLEET_SCOPES?env.ACTAE_FLEET_SCOPES.split(','):undefined) }); }
  private gatewayPath(suffix:string): string { return `/v1/organizations/${encodeURIComponent(this.organizationId)}${suffix}`; }
  private async token(): Promise<string> { if (this.fleetToken && Date.now() < this.expiresAt) return this.fleetToken; if (!this.exchange) this.exchange=this.exchangeToken(); try { return await this.exchange; } finally { this.exchange=undefined; } }
  private async exchangeToken(): Promise<string> { const r=await this.raw('POST','/api/v1/fleet/token',{purpose:'fleet_access',organization_id:this.organizationId,scopes:this.requestedScopes},{Authorization:`Bearer ${this.organizationToken}`},false,{},false,this.tokenEndpoint); const m=r as Record<string,unknown>; const t=m.token ?? m.access_token; if(typeof t!=='string') throw new AuthError('fleet token exchange returned no access token'); this.fleetToken=t; const seconds=typeof m.expires_in==='number'?m.expires_in:300; this.expiresAt=Date.now()+Math.max(0,seconds-15)*1000; return t; }
  private async raw(method:string,path:string,body?:unknown,extra:Record<string,string>={},auth=true, o: FleetRequestOptions={}, retried=false, baseUrl=this.endpoint):Promise<JsonValue>{ const h:Record<string,string>={...extra}; if(auth)h.Authorization=`Bearer ${await this.token()}`; if(o.instanceId)h['X-Actae-Instance-Id']=o.instanceId; if(o.idempotencyKey)h['Idempotency-Key']=o.idempotencyKey; if(o.confirmTarget)h['X-Actae-Confirm-Target']=o.confirmTarget; const r=await this.fetcher(baseUrl+path,{method,headers:{'content-type':'application/json',...h},body:body===undefined?undefined:JSON.stringify(body),signal:o.signal}); const txt=await r.text(); let v:JsonValue; try{v=txt?parseJson(txt):{};}catch{v={message:txt};} if(r.status===401){this.fleetToken=undefined;this.expiresAt=0;if(auth&&!retried)return this.raw(method,path,body,extra,auth,o,true,baseUrl);throw new AuthError(String((v as any).message??'Authentication failed'));} if(!r.ok)throw new APIError(r.status,String((v as any).message??txt)); return v; }
  instances(o?:FleetRequestOptions){return this.raw('GET',this.gatewayPath('/instances'),undefined,{},true,o);}
  async capabilities(o: FleetRequestOptions = {}): Promise<JsonValue> { const key=o.instanceId??''; if(!o.instanceId) throw new Error('instanceId is required for fleet capabilities'); const cached=this.capabilitiesCache.get(key); if(cached!==undefined)return cached; try { const value=await this.raw('GET',this.gatewayPath(`/instances/${encodeURIComponent(o.instanceId)}/capabilities`),undefined,{},true,o); this.capabilitiesCache.set(key,value); return value; } catch (err) { if (err instanceof APIError && err.statusCode===426) this.capabilitiesCache.delete(key); throw err; } }
  async ensureOperation(operationId:string,o: FleetRequestOptions = {}): Promise<void> { const caps=await this.capabilities(o); if(!caps||typeof caps!=='object'||Array.isArray(caps))return; const m=caps as Record<string,JsonValue>; let advertised=m.supported_fleet_operations; if(advertised===undefined&&m.capabilities&&typeof m.capabilities==='object'&&!Array.isArray(m.capabilities)){const inner=m.capabilities as Record<string,JsonValue>;advertised=inner.operations??inner.operation_ids;} advertised??=m.operations??m.operation_ids??m.supported_operations; if(!Array.isArray(advertised))return; if(!advertised.some((x)=>x===operationId))throw new APIError(426,`unsupported API operation: ${operationId}`); }
  forInstance(instanceId: string): FleetSessionTransport { if(!instanceId) throw new Error('instanceId is required'); return new FleetSessionTransport(this, instanceId); }
  /** Invoke any operation listed in spec/api-parity/v1/manifest.json. */
  async call(method:string,path:string,body?:unknown,o: FleetRequestOptions & { query?: Record<string,string|number|undefined>; operationManifestId?: string } = {}) { const q=new URLSearchParams(); for(const[k,v] of Object.entries(o.query??{})) if(v!==undefined) q.set(k,String(v)); const resolved=path+(q.size?'?'+q:''); if(o.operationManifestId){const op=manifestOperation(o.operationManifestId); if(!op.fleetSupported) throw new APIError(426,`unsupported API operation: ${o.operationManifestId}`); if(op.confirmation&&!o.confirmTarget) throw new Error(`confirmTarget is required for ${o.operationManifestId}`);} else if ((method.toUpperCase()==='DELETE'||path.replace(/\/$/,'').endsWith('/cancel'))&&!o.confirmTarget) throw new Error('confirmTarget is required for destructive fleet operations'); if(o.operationManifestId)await this.ensureOperation(o.operationManifestId,o); return this.raw(method,resolved,body,{},true,o); }
  async callOperation(operationId:string, opts: { instanceId?: string; pathParams?: Record<string,string|number>; body?: unknown; query?: Record<string,string|number|undefined>; idempotencyKey?: string; confirmTarget?: string } = {}): Promise<JsonValue> {
    const op: ManifestOperation = manifestOperation(operationId);
    // PR-016: auth/session/dashboard operations are NOT fleet commands — fail
    // locally before any network I/O.
    if (!op.fleetSupported) throw new APIError(426,`unsupported API operation: ${operationId}`);
    let path=op.path;
    const names=[...path.matchAll(/\{([^}]+)\}/g)].map((m)=>m[1] ?? '').filter(Boolean); const values=opts.pathParams??{};
    for(const name of names){if(values[name]===undefined)throw new Error(`missing path parameter for ${operationId}: ${name}`);path=path.replace(`{${name}}`,encodeURIComponent(String(values[name])));}
    for(const name of Object.keys(values))if(!names.includes(name))throw new Error(`unknown path parameter for ${operationId}: ${name}`);
    if (!opts.instanceId) throw new Error(`instanceId is required for fleet operation ${operationId}`);
    // Confirmation is manifest-driven (not hardcoded to DELETE).
    if (op.confirmation && !opts.confirmTarget) throw new Error(`confirmTarget is required for ${operationId}`);
    const headers: Record<string,string> = {}; const key = opts.idempotencyKey ?? (op.action === 'read' ? undefined : newUUID());
    const envelope = { path_params: values, query: opts.query ?? {}, body: opts.body ?? {} };
    return this.raw('POST',this.gatewayPath(`/instances/${encodeURIComponent(opts.instanceId)}/ops/${encodeURIComponent(operationId)}`),envelope,headers,true,{instanceId:undefined,idempotencyKey:key,confirmTarget:opts.confirmTarget});
  }
  record(instanceId:string,channelId:string,eventType:string,payload:JsonValue,operationId?:string,o: FleetRequestOptions={}){return this.raw('POST',this.gatewayPath(`/instances/${encodeURIComponent(instanceId)}/events`),{channel_id:channelId,event_type:eventType,payload,...(operationId?{operation_id:operationId}:{})},{},true,{...o,idempotencyKey:o.idempotencyKey??operationId??newUUID()});}
  query(instanceId:string, params:Record<string,JsonValue|undefined>={},o: FleetRequestOptions={}){const query:Record<string,JsonValue>={};for(const[k,v]of Object.entries(params))if(v!==undefined)query[k]=v;return this.raw('POST',this.gatewayPath('/events/query'),{instances:[instanceId],query},{},true,o);}
  async queryPage(instanceId:string, params:Record<string,JsonValue|undefined>={},o: FleetRequestOptions={}, pageToken?:string):Promise<Page<JsonValue>> { const query:Record<string,JsonValue>={};for(const[k,v]of Object.entries(params))if(v!==undefined)query[k]=v; if(query.pagination===undefined)query.pagination='keyset'; const body:Record<string,JsonValue>={instances:[instanceId],query}; if(pageToken)body.page_tokens={[instanceId]:pageToken}; const r=await this.raw('POST',this.gatewayPath('/events/query'),body,{},true,o) as Record<string,JsonValue>; const page=r.page&&typeof r.page==='object'&&!Array.isArray(r.page)?r.page as Record<string,JsonValue>:{}; const tokens=page.next_page_tokens&&typeof page.next_page_tokens==='object'&&!Array.isArray(page.next_page_tokens)?page.next_page_tokens as Record<string,JsonValue>:{}; return {items:Array.isArray(r.events)?r.events:Array.isArray(r.items)?r.items:[],nextPageToken:typeof tokens[instanceId]==='string'?tokens[instanceId] as string:typeof r.next_page_token==='string'?r.next_page_token:undefined}; }
  async *iterQuery(instanceId:string, params:Record<string,JsonValue|undefined>={},o: FleetRequestOptions={}):AsyncGenerator<JsonValue> { let token: string|undefined; do { const page=await this.queryPage(instanceId,params,o,token); for(const item of page.items)yield item; token=page.nextPageToken; } while(token); }
  async queryMany(instanceIds:string[], params:Record<string,JsonValue|undefined>={},o: FleetRequestOptions={}, pageTokens?:Record<string,string>):Promise<PartialResult<JsonValue>> { const query:Record<string,JsonValue>={};for(const[k,v]of Object.entries(params))if(v!==undefined)query[k]=v; if(query.pagination===undefined)query.pagination='keyset'; const body:Record<string,JsonValue>={instances:instanceIds,query}; if(pageTokens&&Object.keys(pageTokens).length>0)body.page_tokens=pageTokens as unknown as JsonValue; const r=await this.raw('POST',this.gatewayPath('/events/query'),body,{},true,o) as Record<string,JsonValue>; const es=Array.isArray(r.errors)?r.errors:[]; const page=r.page&&typeof r.page==='object'&&!Array.isArray(r.page)?r.page as Record<string,JsonValue>:{}; const tokens=page.next_page_tokens&&typeof page.next_page_tokens==='object'&&!Array.isArray(page.next_page_tokens)?page.next_page_tokens as Record<string,JsonValue>:{}; let nextToken:string|undefined; const tokenMap:Record<string,string>={}; for(const [k,v] of Object.entries(tokens)) if(typeof v==='string'){tokenMap[k]=v; if(!nextToken)nextToken=v;} return {items:Array.isArray(r.events)?r.events:Array.isArray(r.items)?r.items:[],errors:es.map((x)=>{const e=x as Record<string,JsonValue>;const msg=typeof e.error==='string'?e.error:'unknown';return {instanceId:typeof e.instance_id==='string'?e.instance_id:'',code:msg,message:msg,retryable:true};}),nextPageToken:instanceIds.length===1&&instanceIds[0]!==undefined&&typeof tokens[instanceIds[0]]==='string'?tokens[instanceIds[0]] as string:nextToken,pageTokens:tokenMap} as PartialResult<JsonValue>; }
  replay(instanceId:string,channelId:string,params:Record<string,string|number|undefined>={},o: FleetRequestOptions={}){return this.callOperation('actae.api.v1.events.replay',{instanceId,pathParams:{channel_id:channelId},query:params});}
  fork(instanceId:string,sourceChannelId:string,newChannelId:string,atCursor:number,operationId?:string,o: FleetRequestOptions={},extra:Record<string,unknown>={}){return this.raw('POST',this.gatewayPath(`/instances/${encodeURIComponent(instanceId)}/forks`),{source_channel_id:sourceChannelId,new_channel_id:newChannelId,at_cursor:atCursor,...extra,...(operationId?{operation_id:operationId}:{})},{},true,{...o,idempotencyKey:o.idempotencyKey??operationId??newUUID()});}
  saveState(instanceId:string,channelId:string,cursor:number,state:JsonValue,o: FleetRequestOptions={}){return this.raw('PUT',this.gatewayPath(`/instances/${encodeURIComponent(instanceId)}/state/${encodeURIComponent(channelId)}`),{channel_id:channelId,cursor,state},{},true,{...o,idempotencyKey:o.idempotencyKey??newUUID()});}
  latestState(instanceId:string,channelId:string,o: FleetRequestOptions={}){return this.callOperation('actae.api.v1.state.load',{instanceId,pathParams:{channel_id:channelId}});}
  async *stream(o: FleetRequestOptions & { params?: Record<string,string|number|undefined> } = {}): AsyncGenerator<JsonValue> {
    const q=new URLSearchParams(); for(const[k,v] of Object.entries(o.params??{})) if(v!==undefined) q.set(k,String(v));
    const h:Record<string,string>={Authorization:`Bearer ${await this.token()}`,Accept:'text/event-stream'}; if(o.instanceId)h['X-Actae-Instance-Id']=o.instanceId;
    const r=await this.fetcher(this.endpoint+this.gatewayPath('/events/stream')+(q.size?'?'+q:''),{headers:h,signal:o.signal}); if(!r.ok||!r.body)throw new APIError(r.status,'fleet stream unavailable');
    const reader=r.body.getReader(); const decoder=new TextDecoder(); let buffer=''; const seen=new Set<string>();
    try { for(;;){const {value,done}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const lines=buffer.split(/\r?\n/);buffer=lines.pop()??'';for(const line of lines){const s=line.startsWith('data:')?line.slice(5).trim():line.trim();if(!s)continue;const item=parseJson(s);if(item&&typeof item==='object'&&!Array.isArray(item)){const m=item as Record<string,JsonValue>;const id=m.event_id??m.id;if(id!==undefined){const key=`${String(m.instance_id??o.instanceId??'')}:${String(id)}`;if(seen.has(key))continue;seen.add(key);if(seen.size>10000)seen.clear();}}yield item;}}} finally {reader.releaseLock();}
  }

  /** Gateway WebSocket stream with one-use ticket rotation and cursor resume.
   * PR-019: the per-connection queue is bounded (frames), the resume cursor
   * preserves 64-bit precision (bigint/string), and AbortSignal cancellation
   * is propagated through connect, ticket fetch, backoff and queue wait. A
   * slow consumer that overflows the queue surfaces a typed `fleet_lag` error
   * with the last safe opaque resume position instead of an unbounded buffer. */
  async *streamWithReconnect(o: FleetStreamReconnectOptions): AsyncGenerator<JsonValue> {
    if (!o.ticket && !o.ticketProvider) throw new Error('ticket or ticketProvider is required for gateway streams');
    const seen = new Set<string>(); let cursor: bigint | string | number | undefined = o.resumeCursor; let ticket = o.ticket;
    let attempts = 0; const max = o.maxReconnectAttempts ?? 5; const cap = o.maxQueueFrames ?? 4096;
    const aborted = () => { if (o.signal?.aborted) throw new Error('aborted'); return false; };
    const sleep = (ms: number) => new Promise<void>((resolve, reject) => { const t = setTimeout(resolve, ms); o.signal?.addEventListener('abort', () => { clearTimeout(t); reject(new Error('aborted')); }, { once: true }); });
    while (true) {
      aborted();
      if (!ticket) {
        if (!o.ticketProvider) throw new Error('gateway stream ticket expired; ticketProvider is required for reconnect');
        ticket = await o.ticketProvider(cursor);
        aborted();
      }
      const q = new URLSearchParams(); for (const [k,v] of Object.entries(o.params??{})) if(v!==undefined) q.set(k,String(v)); q.set('ticket',ticket); if(cursor!==undefined) q.set('resume_cursor',String(cursor));
      const url = new URL(this.endpoint+this.gatewayPath('/events/stream')); url.search = q.toString(); url.protocol=url.protocol==='https:'?'wss:':'ws:';
      const socket = new WebSocket(url.toString()); const queue: JsonValue[]=[]; let wake:(()=>void)|undefined; let closed=false; let failure:Error|undefined;
      socket.on('message',(raw)=>{ try { const item=parseJson(String(raw)); const m=item&&typeof item==='object'&&!Array.isArray(item)?item as Record<string,JsonValue>:undefined; const broadcast=m?.Broadcast&&typeof m.Broadcast==='object'&&!Array.isArray(m.Broadcast)?m.Broadcast as Record<string,JsonValue>:undefined; const payload=broadcast?.payload&&typeof broadcast.payload==='object'&&!Array.isArray(broadcast.payload)?broadcast.payload as Record<string,JsonValue>:undefined; const event=payload?.event&&typeof payload.event==='object'&&!Array.isArray(payload.event)?payload.event as Record<string,JsonValue>:(m?.event&&typeof m.event==='object'&&!Array.isArray(m.event)?m.event as Record<string,JsonValue>:m); if(event){const c=event.cursor;if(c!==undefined&&(typeof c==='number'||typeof c==='bigint'||typeof c==='string'))cursor=c as bigint|string|number;} if(event){const id=event.event_id??event.id;if(id!==undefined){const key=`${String(event.instance_id??o.instanceId??'')}:${String(id)}`;if(seen.has(key))return;seen.add(key);if(seen.size>10000)seen.clear();}} if(queue.length>=cap){ failure=new Error('fleet stream lag: downstream queue overflowed'); socket.close(); } else { queue.push(item); } } catch { /* ignore malformed frames */ } wake?.(); wake=undefined; });
      socket.on('error',(err)=>{failure=err instanceof Error?err:new Error(String(err));wake?.();wake=undefined;}); socket.on('close',()=>{closed=true;wake?.();wake=undefined;});
      const onAbort=()=>{failure=new Error('aborted');wake?.();wake=undefined;}; o.signal?.addEventListener('abort',onAbort,{once:true});
      try { await new Promise<void>((resolve,reject)=>{ const onOpen=()=>{socket.off('error',onError);resolve();}; const onError=(e:Error)=>{socket.off('open',onOpen);reject(e);}; socket.once('open',onOpen); socket.once('error',onError); }); ticket=undefined; attempts=0;
        while(!closed||queue.length){while(!queue.length&&!closed&&!failure)await new Promise<void>((resolve)=>{wake=resolve;});if(failure)throw failure;if(queue.length)yield queue.shift()!;}
      } catch (err) { o.signal?.removeEventListener('abort',onAbort); socket.close(); if (o.signal?.aborted) throw err; if(attempts>=max) throw err; attempts++; await sleep(Math.min(30000,(o.reconnectDelayMs??250)*2**(attempts-1))); continue; } finally { o.signal?.removeEventListener('abort',onAbort); socket.close(); }
      if(attempts>=max) return; attempts++; await sleep(Math.min(30000,(o.reconnectDelayMs??250)*2**(attempts-1)));
    }
  }
}

/** Direct-client shaped backend for AgentSession. Lifecycle logic stays in session.ts. */
export class FleetSessionTransport {
  constructor(private readonly fleet: FleetClient, readonly instanceId: string) {}
  private command(operationId:string,opts: { pathParams?: Record<string,string|number>; body?: unknown; query?: Record<string,string|number|undefined> } = {}) { return this.fleet.callOperation(operationId,{instanceId:this.instanceId,...opts}); }
  async record(channelId:string,eventType:string,payload:JsonValue,opts:Record<string,unknown>={}) : Promise<Event> {
    const body:Record<string,unknown>={channel_id:channelId,event_type:eventType,payload,metadata:{actor:opts.actor??'',agent_id:opts.agentId,user_id:opts.userId,metadata:opts.metadata}};
    if(opts.operationId!==undefined)body.operation_id=opts.operationId;if(opts.stepNumber!==undefined)body.step_number=opts.stepNumber;if(opts.dependencies!==undefined)body.dependencies=opts.dependencies;
    const r=await this.fleet.callOperation('actae.api.v1.events.record',{instanceId:this.instanceId,body,idempotencyKey:typeof opts.operationId==='string'?opts.operationId:undefined}) as Record<string,JsonValue>; const d=r.data&&typeof r.data==='object'&&!Array.isArray(r.data)?r.data as Record<string,JsonValue>:r; return eventFromRecord((d.event as Record<string,JsonValue>)??d);
  }
  async replay(channelId:string,opts:Record<string,unknown>={}):Promise<Event[]> { const q:Record<string,string|number|undefined>={cursor:typeof opts.cursor==='number'?opts.cursor:undefined,limit:typeof opts.limit==='number'?opts.limit:undefined,event_type:typeof opts.eventType==='string'?opts.eventType:undefined}; const r=await this.fleet.callOperation('actae.api.v1.events.replay',{instanceId:this.instanceId,pathParams:{channel_id:channelId},query:q}) as Record<string,JsonValue>; const d=r.data&&typeof r.data==='object'&&!Array.isArray(r.data)?r.data as Record<string,JsonValue>:r; return Array.isArray(d.events)?d.events.map((e)=>eventFromReplay(e as Record<string,JsonValue>)):[]; }
  async saveState(channelId:string,cursor:number,state:JsonValue,opts:Record<string,unknown>={}):Promise<number> { const r=await this.fleet.saveState(this.instanceId,channelId,cursor,state,opts as FleetRequestOptions) as Record<string,JsonValue>; const raw=r.data; const d=raw&&typeof raw==='object'&&!Array.isArray(raw)?raw as Record<string,JsonValue>:r; return Number(d.version??0); }
  async latestState(channelId:string):Promise<{cursor:number;state:JsonValue}|undefined> { const r=await this.fleet.callOperation('actae.api.v1.state.load',{instanceId:this.instanceId,pathParams:{channel_id:channelId}}) as Record<string,JsonValue>; const d=r.data&&typeof r.data==='object'&&!Array.isArray(r.data)?r.data as Record<string,JsonValue>:r; return typeof d.cursor==='number'?{cursor:d.cursor,state:d.state??null}:undefined; }
  async fork(source:string,child:string,cursor:number,opts:Record<string,unknown>={}):Promise<ForkReceipt> { const extra:Record<string,unknown>={};if(opts.displayName!==undefined)extra.display_name=opts.displayName;if(opts.reason!==undefined)extra.reason=opts.reason;if(opts.experimentMetadata!==undefined)extra.experiment_metadata=opts.experimentMetadata;if(opts.manifest!==undefined)extra.manifest=opts.manifest;if(opts.expectedVersion!==undefined)extra.expected_version=opts.expectedVersion;if(opts.expectedCursor!==undefined)extra.expected_cursor=opts.expectedCursor; const r=await this.fleet.fork(this.instanceId,source,child,cursor,typeof opts.operationId==='string'?opts.operationId:undefined,{},extra) as Record<string,JsonValue>; return forkReceiptFromDict((r.data as Record<string,JsonValue>)??r); }
  async getChannelMetadata(channelId:string):Promise<ChannelMetadata|undefined> { try { const r=await this.command('actae.api.v1.channels.metadata.get',{pathParams:{channel_id:channelId}}) as Record<string,JsonValue>;return channelMetadataFromDict(r.data&&typeof r.data==='object'&&!Array.isArray(r.data)?r.data as Record<string,JsonValue>:r); } catch(e) { if(e instanceof APIError&&e.statusCode===404)return undefined;throw e; } }
  async updateMetadata(channelId:string,opts:Record<string,unknown>):Promise<ChannelMetadata> { const r=await this.command('actae.api.v1.channels.metadata.put',{pathParams:{channel_id:channelId},body:{channel_id:channelId,...(opts.displayName===undefined?{}:{display_name:opts.displayName}),...(opts.reason===undefined?{}:{reason:opts.reason}),...(opts.experimentMetadata===undefined?{}:{experiment_metadata:opts.experimentMetadata})}}) as Record<string,JsonValue>;const d=r.data&&typeof r.data==='object'&&!Array.isArray(r.data)?r.data as Record<string,JsonValue>:r;return channelMetadataFromDict(d); }
  async resolveStep(channelId:string,step:number):Promise<[string,number,string|undefined]|undefined> { try { const r=await this.command('actae.api.v1.channels.steps.resolve',{pathParams:{channel_id:channelId,step_number:step}}) as Record<string,JsonValue>;const d=r.data&&typeof r.data==='object'&&!Array.isArray(r.data)?r.data as Record<string,JsonValue>:r;return [String(d.channel_id),Number(d.cursor),typeof d.event_id==='string'?d.event_id:undefined]; }catch(e){if(e instanceof APIError&&e.statusCode===404)return undefined;throw e;} }
  async latestStepNumber(channelId:string):Promise<number|undefined> { try { const r=await this.command('actae.api.v1.channels.steps.latest',{pathParams:{channel_id:channelId}}) as Record<string,JsonValue>;const d=r.data&&typeof r.data==='object'&&!Array.isArray(r.data)?r.data as Record<string,JsonValue>:r;return Number(d.last_step_number??0); }catch(e){if(e instanceof APIError&&e.statusCode===404)return undefined;throw e;} }
  setOutcome(channelId:string,outcome:string,score?:number){return this.command('actae.api.v1.channels.outcome.set',{pathParams:{channel_id:channelId},body:{outcome,...(score===undefined?{}:{score})}});}
  promoteChannel(channelId:string){return this.command('actae.api.v1.forks.promote',{pathParams:{channel_id:channelId}});}
  createExperiment(name:string,opts:Record<string,unknown>={}){return this.command('actae.api.v1.experiments.create',{body:{name,...(opts.description===undefined?{}:{description:opts.description}),...(opts.baselineChannelId===undefined?{}:{baseline_channel_id:opts.baselineChannelId})}});}
  addExperimentMember(groupId:string,channelId:string,opts:Record<string,unknown>={}){return this.command('actae.api.v1.experiments.members.add',{pathParams:{group_id:groupId},body:{channel_id:channelId,...(opts.role===undefined?{}:{role:opts.role}),...(opts.declaredDelta===undefined?{}:{declared_delta:opts.declaredDelta})}});}
}
